-- MySQL Script generated by MySQL Workbench
-- Fri Aug  4 14:41:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`nouns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nouns` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nouns` (
  `id_noun` INT NULL,
  `noun` VARCHAR(45) NULL,
  PRIMARY KEY (`id_noun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`descriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`descriptions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`descriptions` (
  `id_description` INT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_description`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tooked_combinstions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tooked_combinstions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tooked_combinstions` (
  `id_tc` INT NULL,
  `tc_noun` INT NULL,
  `tc_description` INT NULL,
  PRIMARY KEY (`id_tc`),
  INDEX `id_nouns_tooked_idx` (`tc_noun` ASC) VISIBLE,
  INDEX `id_description_tooked_idx` (`tc_description` ASC) VISIBLE,
  CONSTRAINT `id_nouns_tooked`
    FOREIGN KEY (`tc_noun`)
    REFERENCES `mydb`.`nouns` (`id_noun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_description_tooked`
    FOREIGN KEY (`tc_description`)
    REFERENCES `mydb`.`descriptions` (`id_description`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
